### ISSUE TITLE
Different order of categories in the radial chart and tooltip

### ISSUE THREAD

**Issue by gretacv** [mongabay/reforestation-catalogue#16]
The image example shows when `Institutional` is selected, it is the orange line. I was expecting the orange line to be `social`, following the order in the tooltip or the second ring (from the inside) to be the orange one.
![image](https://user-images.githubusercontent.com/11423895/116562143-3559b680-a903-11eb-9638-87c80c465600.png)

**Comment by 01painadam** [comment]
Is there an order it should be?

It seems the Object for the tooltip get sorted alphabetically

**Comment by gretacv** [comment]
[designs](https://www.figma.com/proto/IZGL3yeQyqxniVqWjQw1EK/Mongabay-Restoration?node-id=256%3A2&scaling=min-zoom&page-id=0%3A1) show the order: Context, Ecological, Economic, Social, Institutional.

**Comment by 01painadam** [comment]
Done, PR in coming in 5 mins @pablopareja

**Comment by WillieShubert** [comment]
Are you planning to change the color scheme of the rings at all? I don't quite understand the selection logic for the different colors.
