### ISSUE TITLE
Embed URLs (project list and filters)

### ISSUE THREAD

**Issue by pablopareja** [mongabay/reforestation-catalogue#19]

**Comment by WillieShubert** [comment]
It would be great to be able to embed the following items into other pages. Is it possible to provide components like these?

### Filters 
<img width="362" alt="Filters_embed" src="https://user-images.githubusercontent.com/3870349/116630519-275a6480-a908-11eb-8616-42db0334d997.png">

### single project 
<img width="289" alt="single-project_embed" src="https://user-images.githubusercontent.com/3870349/116630554-3ccf8e80-a908-11eb-8e6b-2a90f178eefa.png">

### multi project
<img width="923" alt="multi-project_embed" src="https://user-images.githubusercontent.com/3870349/116630587-4b1daa80-a908-11eb-902c-f9beb5c51da8.png">

**Comment by pablopareja** [comment]
Implemented here: https://github.com/mongabay/reforestation-catalogue/pull/33 ✅ 
_(Information about how the URLs should be build for each of the embed types can be found in the PR description)_
