### ISSUE TITLE
Grey out fingerprints of finalised projects

### ISSUE THREAD

**Issue by osesenar** [mongabay/reforestation-catalogue#23]
To help users discard finalised projects (if they're looking to donate to an ongoing project), the fingerprints of finalised projects should be greyed out. The logic would be something like: `if endDate and endDate < currentYear`, then the circles are grey (#DEDEDE), except for the highlighted one which stays in the same orange shade.
Attaching a screenshot of the design:

<img width="366" alt="Screenshot 2021-04-30 at 10 17 00" src="https://user-images.githubusercontent.com/58157123/116668055-36d7bd00-a99d-11eb-9f02-e581f4d5ef50.png">

**Comment by pablopareja** [comment]
Done here: https://github.com/mongabay/reforestation-catalogue/pull/29 ✅
