### ISSUE TITLE
Drop the 's from the title page.

### ISSUE THREAD

**Issue by osesenar** [mongabay/reforestation-catalogue#24]
It should read `MONGABAY REFORESTATION DIRECTORY` instead of `MONGABAY's...` as per [Willie's comment](https://basecamp.com/1756858/projects/17212341/messages/95391765#comment_811854150) on basecamp.

<img width="833" alt="Screenshot 2021-04-30 at 13 03 22" src="https://user-images.githubusercontent.com/58157123/116686791-9e4d3700-a9b4-11eb-9a92-e270fd313777.png">

(Also, the line below the title is barely visible, I'd remove it since we have the green banner, but this is very optional).

**Comment by pablopareja** [comment]
Done in the `main` branch ✅
