### ISSUE TITLE
Include favicon and og image

### ISSUE THREAD

**Issue by osesenar** [mongabay/reforestation-catalogue#25]
Favicon (which is also used in the About page) and og image available on [figma](https://www.figma.com/file/IZGL3yeQyqxniVqWjQw1EK/Mongabay-Restoration?node-id=2%3A2).

<img width="820" alt="Screenshot 2021-04-30 at 13 06 58" src="https://user-images.githubusercontent.com/58157123/116687114-f4ba7580-a9b4-11eb-99dd-acdd9acc31cb.png">

**Comment by pablopareja** [comment]
Thanks for creating the issue @osesenar 👍 
However, I would need a `.ico` file for the favicon. I could look up how to export it to that format but I wanted to double check with you in case there's some kind of configuration I need to consider when doing that? 🤔

**Comment by pablopareja** [comment]
_Update: og image added_
![image](https://user-images.githubusercontent.com/545342/116892547-37d44d00-ac30-11eb-8402-08aa4049af34.png)

**Comment by pablopareja** [comment]
Favicon added to the producion site ✅
